# Test your FastAPI endpoints

GET http://127.0.0.1:8000/bathroom/get
Accept: application/json

###

GET http://127.0.0.1:8000/bathroom/get/1/average
Accept: application/json

###

PUT http://127.0.0.1:8000/bathroom/change/1/false
Accept: application/json

###
